services:
  - type: web
    name: content-generator-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
